name: Build MRS

on:
  push:
    paths:
      - 'data/geo/geosite/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build geo_mrs_gen
      run: |
        git clone https://github.com/MetaCubeX/meta-rules-dat.git
        cd meta-rules-dat/tools/geo_mrs_gen
        go build -o geo_mrs_gen
        mkdir -p ../../../output
        ./geo_mrs_gen -d ../../../data/geo -o ../../../output

    - name: Upload MRS result
      uses: actions/upload-artifact@v3
      with:
        name: mrs-output
        path: output
